name: admin
description: A new Flutter project.

publish_to: "none"

version: 1.0.8+1

environment:
  sdk: ">=2.19.2 <3.0.0"

dependencies:
  auto_size_text: ^3.0.0
  cached_network_image: ^3.2.3
  carousel_slider: ^4.2.1
  cloud_firestore: ^4.4.4
  cross_file: ^0.3.3+4
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  equatable: ^2.0.5
  file_picker: ^5.2.7
  firebase_auth: ^4.2.10
  firebase_core: ^2.7.1
  firebase_storage: ^11.1.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.0.2
  flutter_expandable_table: ^1.1.1
  flutter_riverpod: ^2.3.1
  flutter_svg: ^2.0.3
  google_fonts: ^4.0.3
  http: ^0.13.5
  logging: ^1.1.1
  razorpay_web: ^1.3.6
  responsive_builder: ^0.6.4
  routemaster: ^1.0.1
  url_launcher: ^6.1.10

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/

  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins/Poppins-Thin.ttf
          weight: 100
        - asset: fonts/Poppins/Poppins-ExtraLight.ttf
          weight: 200
        - asset: fonts/Poppins/Poppins-Light.ttf
          weight: 300
        - asset: fonts/Poppins/Poppins-Regular.ttf
          weight: 400
        - asset: fonts/Poppins/Poppins-Medium.ttf
          weight: 500
        - asset: fonts/Poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: fonts/Poppins/Poppins-Bold.ttf
          weight: 700
        - asset: fonts/Poppins/Poppins-ExtraBold.ttf
          weight: 800
        - asset: fonts/Poppins/Poppins-Black.ttf
          weight: 900
